project:
  type: website
  output-dir: docs

website:
  title: "ninahayf.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
